# Generated by Django 4.2.1 on 2023-06-27 11:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('prof', models.CharField(max_length=50)),
                ('nbcredit', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('secrete_key', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
