# Generated by Django 4.2.1 on 2023-07-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_cours_image_remove_etudiant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='courssuivi',
        ),
    ]
